export const financialCalligraphyAbi = [
  "error AlreadyMinted()",
  "error BadCommitFee()",
  "error BadDiceResult()",
  "error BadMintPayment()",
  "error BadSignature()",
  "error InvalidTransferValidatorContract()",
  "error MaxAttemptsReached()",
  "error MessageUsed()",
  "error NonceUsed()",
  "error NotCommitted()",
  "error SoldOut()",
  "error ZeroAddress()",
  "event DiceMinted(address indexed user, uint256 diceResult, uint256 amountMinted)",
  "event MintCommitted(address indexed user, uint256 attempt)",
  "event TokenSeedCreated(uint256 indexed tokenId, uint256 seed)",
  "event Transfer(address indexed from, address indexed to, uint256 indexed tokenId)",
  "function MAX_SUPPLY() view returns (uint256)",
  "function attemptCount(address) view returns (uint256)",
  "function balanceOf(address owner) view returns (uint256)",
  "function commitFee() view returns (uint256)",
  "function commitToMint() payable",
  "function mintPrice() view returns (uint256)",
  "function mintState(address) view returns (uint8)",
  "function mintWithDice(uint256 diceResult, uint256 nonce, bytes signature) payable",
  "function ownerOf(uint256 tokenId) view returns (address)",
  "function tokenURI(uint256 tokenId) view returns (string)",
  "function totalMinted() view returns (uint256)"
];
